project_id = "qfqowhetrxritoyjzzcz"

[functions.health-check]
verify_jwt = false

[functions.oauth-twitter]
verify_jwt = false

[functions.oauth-linkedin]
verify_jwt = false

[functions.oauth-instagram]
verify_jwt = false

[functions.oauth-facebook]
verify_jwt = false

[functions.oauth-youtube]
verify_jwt = false

[functions.oauth-threads]
verify_jwt = false

[functions.oauth-tiktok]
verify_jwt = false

[functions.meta-deauthorize]
verify_jwt = false

[functions.meta-data-deletion]
verify_jwt = false

[functions.publish-post]
verify_jwt = true

[functions.run-scheduled-posts]
verify_jwt = false

[functions.upload-media]
verify_jwt = true

[functions.send-team-invitation]
verify_jwt = true

[functions.accept-team-invitation]
verify_jwt = true

[functions.send-feedback]
verify_jwt = true

[functions.send-password-reset]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.signup-user]
verify_jwt = false
